---

hostname: rtr-4
domain_name: lab.local

ntp:
  - '216.239.35.8'

loopback:
  address: 10.255.0.4
  mask: 255.255.255.255

interfaces:
  0/1:
    alias: connection rtr-2
    address: 10.0.254.1
    mask: 255.255.255.252

  0/2:
    alias: connection rtr-3
    address: 10.0.254.5
    mask: 255.255.255.252

bgp:
  asn: 65002
  neighbor:
    - {address: 10.0.254.2, remote_as: 65000}
    - {address: 10.0.254.6, remote_as: 65000}
  networks:
    - {network: 10.0.254.0, mask: 255.255.255.252}
    - {network: 10.0.254.4, mask: 255.255.255.252}
    - {network: 10.255.0.4, mask: 255.255.255.255}
  maxpath: 2
